### ISSUE TITLE
Building kivy recipe fails

### ISSUE THREAD

**Issue by zwyuan** [mobile-insight/mobileinsight-dev#2]
On a recent install, `kivy` recipe fails to build in the `bento/ubuntu16.04` VM environment.

```
[INFO]:    Building kivy for armeabi
('name is', None, <class 'pythonforandroid.recipes.kivy.KivyRecipe'>)
[INFO]:    kivy apparently isn't already in site-packages
[INFO]:    Cythonizing anything necessary in kivy
ccache found, will optimize builds
('path is', '/home/vagrant/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/:/home/vagrant/android-ndk-r10e/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/home/vagrant/android-ndk-r10e:/home/vagrant/android-sdk/tools:/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/vagrant/android-ndk-r10e:/home/vagrant/android-sdk:/home/vagrant/android-sdk/tools:/home/vagrant/android-sdk/tools/bin:/home/vagrant/android-sdk/platform-tools')
[INFO]:    -> directory context /home/vagrant/.python-for-android/build/other_builds/kivy-pygame-python2/armeabi/kivy
[INFO]:    -> running python.host -c import sys; print(sys.path)
('cwd is', '/home/vagrant/.python-for-android/build/other_builds/kivy-pygame-python2/armeabi/kivy')
[INFO]:    Trying first build of kivy to get cython files: this is expected to fail
[INFO]:    -> running python.host setup.py build_ext -v
           working:  NameError: global name 'FileNotFoundError' is not defined                                                                Exception in thread background thread for pid 6603:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:

  RAN: /home/vagrant/.python-for-android/build/python-installs/mi3/bin/python.host setup.py build_ext -v

  STDOUT:
Using distutils

Cython check avoided.
Using this graphics system: OpenGL ES 2
fatal: Not a git repository (or any of the parent directories): .git
 Traceback (most recent call last):
   File "setup.py", line 962, in <module>
     version=get_version(),
   File "setup.py", line 49, in get_version
     except (CalledProcessError, FileNotFoundError):
 NameError: global name 'FileNotFoundError' is not defined


  STDERR:


()
[INFO]:    kivy first build failed (as expected)
[INFO]:    Running cython where appropriate
[INFO]:    Cythonize kivy/properties.pyx
[INFO]:    -> running cython ./kivy/properties.pyx
           working: kivy/properties.pyx:272:0: 'include/config.pxi' not found                                                                 Exception in thread background thread for pid 6610:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
ErrorReturnCode_1:

  RAN: /usr/local/bin/cython ./kivy/properties.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
           'NumericProperty', 'StringProperty', 'ListProperty',
           'ObjectProperty', 'BooleanProperty', 'BoundedNumericProperty',
           'OptionProperty', 'ReferenceListProperty', 'AliasProperty',
           'DictProperty', 'VariableListProperty', 'ConfigParserProperty')

include "include/config.pxi"
^
------------------------------------------------------------

kivy/properties.pyx:272:0: 'include/config.pxi' not found



  STDERR:


Traceback (most recent call last):
  File "/usr/local/bin/python-for-android", line 9, in <module>
    load_entry_point('python-for-android==0.4', 'console_scripts', 'python-for-android')()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 763, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 344, in __init__
    getattr(self, command_method_name)(unknown)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 93, in wrapper_func
    build_dist_from_args(ctx, dist, dist_args)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/toolchain.py", line 138, in build_dist_from_args
    build_recipes(build_order, python_modules, ctx)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/build.py", line 561, in build_recipes
    recipe.build_arch(arch)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 921, in build_arch
    self.build_cython_components(arch)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 958, in build_cython_components
    self.cythonize_build(env=env)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 992, in cythonize_build
    self.cythonize_file(env, build_dir, join(root, filename))
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/recipe.py", line 983, in cythonize_file
    shprint(cython_command, filename, *self.cython_args, _env=cyenv)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.4-py2.7.egg/pythonforandroid/logger.py", line 173, in shprint
    for line in output:
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 863, in next
    self.wait()
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/local/lib/python2.7/dist-packages/sh-1.12.14-py2.7.egg/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/cython ./kivy/properties.pyx

  STDOUT:

Error compiling Cython file:
------------------------------------------------------------
...
           'NumericProperty', 'StringProperty', 'ListProperty',
           'ObjectProperty', 'BooleanProperty', 'BoundedNumericProperty',
           'OptionProperty', 'ReferenceListProperty', 'AliasProperty',
           'DictProperty', 'VariableListProperty', 'ConfigParserProperty')

include "include/config.pxi"
^
------------------------------------------------------------

kivy/properties.pyx:272:0: 'include/config.pxi' not found



  STDERR:

```

**Comment by zwyuan** [comment]
Fixed by upstream mobileinsight-mobile v3.2.0
