### ISSUE TITLE
编译终止：The SSH command responded with a non-zero exit status.

### ISSUE THREAD

**Issue by cn0xroot** [mobile-insight/mobileinsight-dev#3]
Hi，我这边使用VB+vagrant搭建开发环境的时候出现了这个问题，执行 `vagrant up` 一个多小时以后出现下面的报错：

```
==> default: python-for-android create --dist-name=mi3 --bootstrap=sdl2 --storage-dir=/home/vagrant/.python-for-android --sdk-dir=/home/vagrant/android-sdk --android-api=19 --minsdk=14 --ndk-dir=/home/vagrant/android-ndk-r10e --ndk-version=r10e-rc4 --arch=armeabi-v7a --requirements=pyserial,android,kivy,mobileinsight
==> default: python deploy.py apk debug
==> default: rm: cannot remove 'diag_revealer': No such file or directory
==> default: make[1]: Entering directory '/home/vagrant/mi-dev/mobileinsight-mobile/diag_revealer/qcom/jni'
==> default: ndk-build
==> default: make[1]: ndk-build: Command not found
==> default: Makefile:4: recipe for target 'diag_revealer' failed
==> default: make[1]: Leaving directory '/home/vagrant/mi-dev/mobileinsight-mobile/diag_revealer/qcom/jni'
==> default: make[1]: *** [diag_revealer] Error 127
==> default: rm: cannot remove 'diag_revealer_mtk': No such file or directory
==> default: make[1]: Entering directory '/home/vagrant/mi-dev/mobileinsight-mobile/diag_revealer/mtk/jni'
==> default: ndk-build
==> default: make[1]: ndk-build: Command not found
==> default: Makefile:4: recipe for target 'diag_revealer_mtk' failed
==> default: make[1]: Leaving directory '/home/vagrant/mi-dev/mobileinsight-mobile/diag_revealer/mtk/jni'
==> default: make[1]: *** [diag_revealer_mtk] Error 127
==> default: [INFO]:    Will compile for the following archs: armeabi-v7a
==> default: [INFO]:    Getting Android API version from user argument
==> default: [INFO]:    Available Android APIs are (19)
==> default: [INFO]:    Requested API target 19 is available, continuing.
==> default: [INFO]:    Getting NDK dir from from user argument
==> default: [INFO]:    Got NDK version from from user argument
==> default: [INFO]:    Using Google NDK r10e-rc4
==> default: [INFO]:    Found virtualenv at /usr/local/bin/virtualenv
==> default: [INFO]:    Found the following toolchain versions: ['4.8', '4.9', 'clang3.5', 'clang3.6']
==> default: [INFO]:    Picking the latest gcc toolchain, here 4.9
==> default: [INFO]:    No existing dists meet the given requirements!
==> default: [INFO]:    No dist exists that meets your requirements, so one will be built.
==> default: [INFO]:    Found a single valid recipe set: []
==> default: [INFO]:    Trying to find a bootstrap that matches the given recipes.
==> default: [INFO]:    Found 7 acceptable bootstraps: ['webview', 'webview', 'sdl2', 'sdl2', 'service_only', 'service_only', 'pygame']
==> default: [INFO]:    Using the first of these: webview
==> default: [INFO]:    Found a single valid recipe set: []
==> default: [INFO]:    The selected bootstrap is webview
==> default: [INFO]:    # Creating dist with webview bootstrap
==> default: [INFO]:    Dist will have name mi3 and recipes ()
==> default: [INFO]:    Dist will also contain modules () installed from pip
==> default: stty:
==> default: 'standard input'
==> default: : Inappropriate ioctl for device
==> default: [INFO]:    -> running cp -r /usr/local/lib/python2.7/dist-packages/python_for_and...(and 127 more)
==> default: [INFO]:    -> directory context /home/vagrant/.python-for-android/build/bootstrap_builds/webview
==> default: [INFO]:    <- directory context /home/vagrant/mi-dev/mobileinsight-mobile
==> default: [INFO]:    Recipe build order is []
==> default: [INFO]:    # Downloading recipes
==> default: [INFO]:    # Building all recipes for arch armeabi-v7a
==> default: [INFO]:    # Unpacking recipes
==> default: [INFO]:    # Prebuilding recipes
==> default: [INFO]:    # Building recipes
==> default: [INFO]:    # Biglinking object files
==> default: [INFO]:    Collating object files from each recipe
==> default: [INFO]:    There seem to be no libraries to biglink, skipping.
==> default: [INFO]:    # Postbuilding recipes
==> default: [INFO]:    # Installing pure Python modules
==> default: [INFO]:    There are no Python modules to install, skipping
==> default: [INFO]:    # Creating Android project from build and webview bootstrap
==> default: stty:
==> default: 'standard input'
==> default: : Inappropriate ioctl for device
==> default: [INFO]:    -> running rm -rf /home/vagrant/.python-for-android/dists/mi3
==> default: stty:
==> default: 'standard input'
==> default: : Inappropriate ioctl for device
==> default: [INFO]:    -> running cp -r /home/vagrant/.python-for-android/build/bootstrap_bui...(and 55 more)
==> default: [INFO]:    -> directory context /home/vagrant/.python-for-android/dists/mi3
==> default: [INFO]:    <- directory context /home/vagrant/mi-dev/mobileinsight-mobile
==> default: [INFO]:    Bootstrap running with arch armeabi-v7a
==> default: [INFO]:    -> directory context /home/vagrant/.python-for-android/dists/mi3
==> default: [INFO]:    Copying python distribution
==> default: Traceback (most recent call last):
==> default:   File "/usr/local/bin/python-for-android", line 9, in <module>
==> default:     load_entry_point('python-for-android==0.5.4', 'console_scripts', 'python-for-android')()
==> default:   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 916, in main
==> default:     ToolchainCL()
==> default:   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 517, in __init__
==> default:     getattr(self, args.subparser_name.replace('-', '_'))(args)
==> default:   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 148, in wrapper_func
==> default:     build_dist_from_args(ctx, dist, args)
==> default:   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 195, in build_dist_from_args
==> default:     ctx.bootstrap.run_distribute()
==> default:   File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/bootstraps/webview/__init__.py", line 30, in run_distribute
==> default:     if not exists('private') and not self.ctx.python_recipe.from_crystax:
==> default: AttributeError: 'NoneType' object has no attribute 'from_crystax'
==> default: make_diag command was:
==> default: cd diag_revealer/qcom/jni; rm diag_revealer;make; cd ../../mtk/jni; rm diag_revealer_mtk; make; cd ../../..;
==> default: build command was:
==> default: python-for-android apk --copy-libs --name=MobileInsight --dist-name=mi3 --storage-dir=/home/vagrant/.python-for-android --version=3.2.0 --private=/home/vagrant/mi-dev/mobileinsight-mobile/app --package=net.mobileinsight.app --icon=/home/vagrant/mi-dev/mobileinsight-mobile/resources/icon.png --presplash=/home/vagrant/mi-dev/mobileinsight-mobile/resources/presplash.jpg --orientation=portrait --sdk-dir=/home/vagrant/android-sdk --android-api=19 --minsdk=14 --ndk-dir=/home/vagrant/android-ndk-r10e --ndk-version=r10e-rc4 --arch=armeabi-v7a --whitelist=/home/vagrant/mi-dev/mobileinsight-mobile/config/whitelist.txt --permission WRITE_EXTERNAL_STORAGE --permission READ_EXTERNAL_STORAGE --permission INTERNET --permission RECEIVE_BOOT_COMPLETED --permission ACCESS_WIFI_STATE --permission INSTALL_PACKAGES --permission ACCESS_NETWORK_STATE --permission ACCESS_FINE_LOCATION --permission ACCESS_COARSE_LOCATION
==> default: cp:
==> default: cannot stat 'MobileInsight-3.0.0-debug.apk'
==> default: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
出现这个问题以后，使用用户：vagrant 密码：vagrant进入到VB,发现mobileinsight-core项目的一些脚本还是跑步起来。

**Comment by cn0xroot** [comment]
```
agrant provision
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
==> default: Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
==> default: Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
==> default: Get:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
==> default: Fetched 306 kB in 3s (97.3 kB/s)
==> default: Reading package lists...
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: build-essential is already the newest version (12.1ubuntu2).
==> default: pkg-config is already the newest version (0.29.1-0ubuntu1).
==> default: ruby is already the newest version (1:2.3.0+1).
==> default: ant is already the newest version (1.9.6-1ubuntu1).
==> default: git is already the newest version (1:2.7.4-0ubuntu1.3).
==> default: 0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default:
==> default: Reading state information...
==> default: autoconf is already the newest version (2.69-9).
==> default: automake is already the newest version (1:1.15-4ubuntu1).
==> default: libtool is already the newest version (2.4.6-0.1).
==> default: zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
==> default: 0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: bison is already the newest version (2:3.0.4.dfsg-1).
==> default: ccache is already the newest version (3.2.4-1).
==> default: flex is already the newest version (2.6.0-11).
==> default: byacc is already the newest version (20140715-1).
==> default: 0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default:
==> default: Reading state information...
==> default: openjdk-8-jdk is already the newest version (8u131-b11-2ubuntu1.16.04.3).
==> default: openjdk-8-jre is already the newest version (8u131-b11-2ubuntu1.16.04.3).
==> default: 0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: python-dev is already the newest version (2.7.11-1).
==> default: python-setuptools is already the newest version (20.7.0-1).
==> default: python-wxgtk3.0 is already the newest version (3.0.2.0+dfsg-1build1).
==> default: 0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
==> default: Reading package lists...
==> default: Building dependency tree...
==> default:
==> default: Reading state information...
==> default: libbz2-1.0:i386 is already the newest version (1.0.6-8).
==> default: libncurses5:i386 is already the newest version (6.0+20160213-1ubuntu1).
==> default: lib32z1 is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
==> default: libc6:i386 is already the newest version (2.23-0ubuntu9).
==> default: libstdc++6:i386 is already the newest version (5.4.0-6ubuntu1~16.04.5).
==> default: 0 upgraded, 0 newly installed, 0 to remove and 56 not upgraded.
==> default: Successfully installed android-sdk-installer-1.1.1
==> default: Parsing documentation for android-sdk-installer-1.1.1
==> default: Done installing documentation for android-sdk-installer after 0 seconds
==> default: 1 gem installed
==> default: Searching for pip
==> default: Best match: pip 9.0.1
==> default: Processing pip-9.0.1-py2.7.egg
==> default: pip 9.0.1 is already the active version in easy-install.pth
==> default: Installing pip script to /usr/local/bin
==> default: Installing pip2.7 script to /usr/local/bin
==> default: Installing pip2 script to /usr/local/bin
==> default:
==> default: Using /usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg
==> default: Processing dependencies for pip
==> default: Finished processing dependencies for pip
==> default: Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages
==> default: Requirement already satisfied: xmltodict in /usr/local/lib/python2.7/dist-packages
==> default: Requirement already satisfied: pyserial in /usr/local/lib/python2.7/dist-packages
==> default: Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/dist-packages
==> default: Requirement already satisfied: virtualenvwrapper in /usr/local/lib/python2.7/dist-packages
==> default: Requirement already satisfied: cython in /usr/local/lib/python2.7/dist-packages
==> default: Requirement already satisfied: virtualenv-clone in /usr/local/lib/python2.7/dist-packages (from virtualenvwrapper)
==> default: Requirement already satisfied: stevedore in /usr/local/lib/python2.7/dist-packages (from virtualenvwrapper)
==> default: Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from stevedore->virtualenvwrapper)
==> default: Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from stevedore->virtualenvwrapper)
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: mkdir: cannot create directory '/home/vagrant/mi-dev': File exists
==> default: fatal: destination path 'mobileinsight-core' already exists and is not an empty directory.
==> default: fatal: destination path 'mobileinsight-mobile' already exists and is not an empty directory.
==> default: fatal: destination path 'python-for-android' already exists and is not an empty directory.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by zwyuan** [comment]
If you can ssh into Vagrant VM, can you execute the following:

```
# Install python-for-android
cd /home/vagrant/mi-dev/python-for-android
sudo python setup.py install

# Prepare MobileInsight Android app compilation
cd /home/vagrant/mi-dev/mobileinsight-mobile

# Make MobileInsight compilation config
make config

# Use default config to compile a python-for-android distribution
make dist

# Use example keystore to compile and sign a release version of MobileInsight
# keystore and key password: mobileinsight
make apk_debug
```

**Comment by cn0xroot** [comment]
执行`vagrant up`的过程中，不清楚什么原因导致Mac崩溃重启了，怀疑是没有完成全部的编译过程。
删掉虚拟机及相关文件，第二次执行`vagrant up`电脑也是出现了死机的情况。
我先换台电脑试试吧。

**Comment by zwyuan** [comment]
Hi, would you kindly let us know if your issue is resolved?

**Comment by cn0xroot** [comment]
Didn't resolved yet🤣

make config pass,
make dist failed:

```
make dist
python deploy.py dist
python-for-android create --dist-name=mi3 --bootstrap=sdl2 --storage-dir=/home/vagrant/.python-for-android --sdk-dir=/home/vagrant/android-sdk --android-api=19 --minsdk=14 --ndk-dir=/home/vagrant/android-ndk-r10e --ndk-version=r10e-rc4 --arch=armeabi-v7a --requirements=pyserial,android,kivy,mobileinsight
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Getting Android API version from user argument
[ERROR]:   Could not find `android` or `sdkmanager` binaries in Android SDK. Exiting.
Traceback (most recent call last):
  File "/usr/local/bin/python-for-android", line 9, in <module>
    load_entry_point('python-for-android==0.5.4', 'console_scripts', 'python-for-android')()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 916, in main
    ToolchainCL()
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 517, in __init__
    getattr(self, args.subparser_name.replace('-', '_'))(args)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/toolchain.py", line 143, in wrapper_func
    user_ndk_ver=self.ndk_version)
  File "/usr/local/lib/python2.7/dist-packages/python_for_android-0.5.4-py2.7.egg/pythonforandroid/build.py", line 238, in prepare_build_environment
    apis = [s for s in targets if re.match(r'^ *API level: ', s)]
UnboundLocalError: local variable 'targets' referenced before assignment
```

**Comment by cn0xroot** [comment]
Hi, zwyuan, i try it on ubuntu 16.04+VirtualBox 5.2.2 +Vagrant 2.0.1

```
mobileinsight-dev git:(master) ✗ sudo vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'boxcutter/ubuntu1604' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'boxcutter/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/boxcutter/ubuntu1604"]
Error: The requested URL returned error: 404 Not Found
```

https://app.vagrantup.com/boxcutter/boxes/ubuntu1604 it's 404 now

**Comment by cn0xroot** [comment]
maybe need change Vagrantfile line 117: ` config.vm.box = "bento/ubuntu-16.04"` to

`  config.vm.box = "ubuntu/xenial64"`

thanks.

**Comment by zwyuan** [comment]
Hi, thanks for reporting this issue. We will test the box and make updates.

**Comment by cn0xroot** [comment]
You are welcome  .  ^_^

**Comment by cn0xroot** [comment]
Hi 更新一下issues状态：
make dist 异常退出

因为国内需要翻墙，导致需要手动下载sdk-tools-linux-3859397.zip tools_r25.2.5-linux.zip android-ndk-r10e-linux-x86_64.zip 按照Vagrantfile脚本内容安装后，再执行make dist导致报错退出：
```
vagrant@vagrant:~/mi-dev/mobileinsight-mobile$ make config
python deploy.py config
Cloning into 'mobileinsight-libs'...
remote: Counting objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Unpacking objects: 100% (45/45), done.
Checking connectivity... done.
Edit ./config/config.yml to customize your configuration!
vagrant@vagrant:~/mi-dev/mobileinsight-mobile$ make dist
python deploy.py dist
python-for-android create --dist-name=mi3 --bootstrap=sdl2 --storage-dir=/home/vagrant/.python-for-android --sdk-dir=/home/vagrant/android-sdk --android-api=19 --minsdk=14 --ndk-dir=/home/vagrant/android-ndk-r10e --ndk-version=r10e-rc4 --arch=armeabi-v7a --requirements=pyserial,android,kivy,mobileinsight
[INFO]:    Will compile for the following archs: armeabi-v7a
[INFO]:    Getting Android API version from user argument
[INFO]:    Available Android APIs are ()
[WARNING]: Requested API target 19 is not available, install it with the SDK android tool.
[WARNING]: Exiting.
```

**Comment by zwyuan** [comment]
Your log shows that Android APIs are not detected. Either you did not install Android API level 19 (because you only installed sdk tools), or your environment path is not set?

**Comment by cn0xroot** [comment]
Build succeed
